/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as reddalTokenSol from "./ReddalToken.sol";
export type { reddalTokenSol };
export type { ReddalCrowdsale } from "./ReddalCrowdsale";
